### ISSUE TITLE
Bug - p node omitted in Espresso output

### ISSUE THREAD

**Issue by shellyyip** [HipsterBrown/espresso#14]
This coffee input:

``` coffee
render: ->
    D.div {}, [

      D.div { className: 'change-request-form-head' },
        D.h2 {}, 'Success!'
        D.p {}, 'Your change request has been submitted.'

      Actions(
        extraClass: 'btn-container-actions'
        buttonClass: 'btn with-arrow'
        onClick: @submit
        buttonLabel: 'Done'
      )
    ]
```

renders to this (raw output):

``` js
render() {
     return <div><div className='change-request-form-head'>{D.h2({}, 'Success!')}</div><Actions
         extraClass='btn-container-actions'
         buttonClass='btn with-arrow'
         onClick={this.submit}
         buttonLabel='Done' /></div>;
 }
```

Somehow the `p` node from the coffee file was lost when converting to es6. Do you think this is an Espresso bug, or something that may have happened with the React codemod instead?

Output was generated by: 
- `espresso app/assets/javascripts/ui/wizards/ --match .coffee --jsx`
- `jscodeshift -t ../react-codemod/transforms/react-to-react-dom.js <your-path-to>/namely/app/assets/javascripts/`

**Original coffee file:** https://github.com/namely/namely/blob/8826d7f58e46bc6b41cc31ffb3391675bb0f1a57/app/assets/javascripts/ui/workflows/requests/success.coffee

**Raw espresso & jscodeshift output:** https://github.com/namely/namely/pull/5139/commits/0fc60bc7a6469e9316d25f3662db2e347340e786

**Comment by HipsterBrown** [comment]
Ok thanks, I'll take a look at this issue today. 👍

**Comment by HipsterBrown** [comment]
@loudhearted So I found the problem area but it will take some time to fix. A quick fix on the content side (the source coffeescript) would be to wrap the children in an array:

``` coffeescript
render: ->
    D.div {}, [

      D.div { className: 'change-request-form-head' }, [
        D.h2 {}, 'Success!'
        D.p {}, 'Your change request has been submitted.'
      ]

      Actions(
        extraClass: 'btn-container-actions'
        buttonClass: 'btn with-arrow'
        onClick: @submit
        buttonLabel: 'Done'
      )
    ]
```

In the current source, the child components are passed to `D.div` as multiple arguments, rather than an array of children (which is what `espresso` is parsing for). I should have a fix & release today or tomorrow.

**Comment by shellyyip** [comment]
Ahh interesting, great catch! Thanks for looking into it & awesome job overall on Espresso 👍
