### ISSUE TITLE
?= conversion

### ISSUE THREAD

**Issue by bitsofdave** [HipsterBrown/espresso#16]
In `stores/onboarding_session_admin.coffee` line 52:

```
attrs.meta.errors ?= {}
```

gets converted to:

```
if ((base = attrs.meta).errors == null) {
    base.errors = {};
}
```

`base` isn't declared, but it's also unnecessary. I've been converting these to:

```
if (attrs.meta.errors == null) {
    attrs.meta.errors = {};
}
```

**Comment by HipsterBrown** [comment]
Fixed in v1.4.3 release https://github.com/HipsterBrown/espresso/releases/tag/v1.4.3
