### ISSUE TITLE
variable declaration

### ISSUE THREAD

**Issue by bitsofdave** [HipsterBrown/espresso#18]
In `actions/onboarding_session_index.coffee`:

If attrs is used in two different functions like:

```
Flux.createActions(
  fetch: () ->
    attrs = {}

  remind: () ->
    $.ajax(...).then((response) ->
      attrs = {}
    )
)
```

It converts into:

```
Flux.createActions({
  fetch() {
    var attrs = {}
  },

  remind() {
    $.ajax(...).then(response => {
      attrs = {}
    }
  }
```

The `attrs` in `remind()` don't get a `var` or `let`.

**Comment by HipsterBrown** [comment]
Should be fixed with v1.4.2 https://github.com/HipsterBrown/espresso/releases/tag/v1.4.2
