### ISSUE TITLE
unicode conversion?

### ISSUE THREAD

**Issue by bitsofdave** [HipsterBrown/espresso#21]
Coffee:

```
D.span { className: 'remind-icon ic', onClick: @handleClick, 'data-obj_id': @props.objID }, '\ue605'
```

Becomes:

```
<span
  className='remind-icon ic'
  onClick={this.handleClick}
  data-obj_id={this.props.objID}></span>
```

Not sure if `'\ue605'` becoming `` is correct or not.

**Comment by HipsterBrown** [comment]
This is an underlying issue (could be called a bug) within `jscodeshift` evaluating unicode characters instead of showing giving the String Literal version as the `value`.  Replacing the evaluated unicode character with the escaped value, i.e. `'\ue605'`

**Comment by bitsofdave** [comment]
Ended up using this which appears to work:

```
<span
  className='remind-icon ic'
  onClick={this.handleClick}
  data-obj_id={this.props.objID}>{'\ue605'}</span>
```
