### ISSUE TITLE
ternary conversion

### ISSUE THREAD

**Issue by bitsofdave** [HipsterBrown/espresso#23]
Coffee:

```
padding = @props.noPadding ? 0 : 20
```

Becomes:

```
var padding = (ref = this.props.noPadding) != null ? ref : {
  0: 20
};
```

**Comment by HipsterBrown** [comment]
According to [the documentation](http://coffeescript.org/#conditiona):

> There is no explicit ternary statement in CoffeeScript — you simply use a regular if statement on a single line.

So the example coffeescript is invalid, making it unrecognizable in the JavaScript source code to convert it to a proper ternary statement. 

Please make note this if you come across it in future conversions.
