### ISSUE TITLE
Target React.createElement

### ISSUE THREAD

**Issue by HipsterBrown** [HipsterBrown/espresso#6]
At the moment, the `jsx` transformer only targets `React.createFactory` and `React.DOM`/`D` `CallExpressions` to convert to the JSX syntax. Targeting `React.createElement` should be a similar process to `React.DOM`, only looking for 3 arguments, at most, instead of 2.

**Comment by RSO** [comment]
I would propose replacing the existing JSX transformation with the one that's written in https://github.com/reactjs/react-codemod/blob/master/transforms/create-element-to-jsx.js

I will create a PR to use that transformation!
